export type InvoiceType = 'Alış' | 'Satış';

export class Invoice {
  public id?: number;  // Optional, since the Id is generated by the server
  public type: InvoiceType;  
  public companyName: string;
  public description: string;
  public amount: number;
  public vat: number;
  public date: Date;
  public siteCode: string;
  public invoiceNumber: string;

  constructor(
    type: InvoiceType,
    companyName: string,
    description: string,
    amount: number,
    vat: number,
    date: Date,
    siteCode: string,
    invoiceNumber: string
  ) {
    this.type = type;
    this.companyName = companyName;
    this.description = description;
    this.amount = amount;
    this.vat = vat;
    this.date = date;
    this.siteCode = siteCode;
    this.invoiceNumber = invoiceNumber;
  }
}
